# Generated by Django 5.2.4 on 2025-07-29 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alcoholic', models.BooleanField(default=False)),
                ('beer_friendly', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='high_consume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ratio_consumo',
            field=models.FloatField(default=1, help_text='Cuántas unidades de este producto consume una persona promedio en un día. Ej: 1.0 = 1 unidad por persona por día.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventtype'),
        ),
    ]
