# Generated by Django 5.2.4 on 2025-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventtype_group_high_consume_product_ratio_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
