# Generated by Django 5.1.2 on 2024-10-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useraccount_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
