# Generated by Django 5.2.4 on 2025-07-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratio_consumo',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del producto (ingredientes, uso, etc.) para ayudar a OpenAI a planificar mejor'),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de unidades individuales que contiene el paquete. Ej: 6 para un pack de 6 latas', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Peso total del paquete del producto (en kilogramos). Ej: 0.5 para 500 gramos', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_per_unit_kg',
            field=models.FloatField(blank=True, help_text='Peso de una unidad del producto, si aplica (en kilogramos). Ej: 0.33 para una lata de 330 ml', null=True),
        ),
    ]
