# Generated by Django 5.1.2 on 2025-07-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_useraccount_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='group',
        ),
    ]
