# Generated by Django 5.2.4 on 2025-07-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='event_type',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
