# Generated by Django 5.1.2 on 2025-07-07 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='duration',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='num_person',
            new_name='people_count',
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='core.group'),
        ),
    ]
