# Generated by Django 5.2.4 on 2025-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_group_event_type_delete_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción libre del plan del grupo. Por ejemplo: lo que quieren comer cada día o el tipo de evento'),
        ),
    ]
