# Generated by Django 5.1.2 on 2025-07-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_duration_group_duration_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_id',
            new_name='id',
        ),
    ]
